site_name: pointers.py
site_url: https://pointerspy.netlify.app/
nav:
    - Home: index.md
    - Getting Started: getting_started.md
    - Using Pointers: using_pointers.md
    - Allocation: allocation.md
    - C Bindings: bindings.md
    - CPython ABI Bindings: cpython_bindings.md
    - Making a Program: making_a_program.md
    - Reference: reference.md
theme: readthedocs

plugins:
    - mkdocstrings:
          handlers:
              python:
                  paths: [src] # search packages in the src folder
